FROM node:20-alpine as development

WORKDIR /app

# Create non-root user
RUN addgroup -g 1001 nodejs && \
  adduser -S nodejs -u 1001 -G nodejs

COPY package*.json ./

RUN npm install

COPY . .

EXPOSE 3000

CMD ["npm", "run", "dev"]
